### ISSUE TITLE
Program points to an invalid website to register

### ISSUE THREAD

**Issue by facundobatista** [facundobatista/encuentro#27]
When I try to register:
Aplicación -> preferencias -> conectate -> registrate aquí 

It points me to a invalid website :(

Any fixes?
Thx

https://usuarios.educ.ar/cuentas/registro/index?servicio=conectate

Error 404

La dirección que estas buscando no existe.

Probá ingresar a educ.ar

Por cualquier consulta podés llamarnos al: 0800 444 1115

Launchpad Details: [#LP1731307](https://bugs.launchpad.net/bugs/1731307) Vagner Rener - 2017-11-09 17:00:52 +0000

**Comment by sansen** [comment]
I'm closing this issue as conectate backend no longer exists.
